# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Avidemux.Avidemux
PackageVersion: 2.8.1
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
InstallerSuccessCodes:
- 1223
UpgradeBehavior: install
ReleaseDate: 2022-09-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mean00/avidemux2/releases/download/2.8.1/Avidemux_2.8.1.VC++.64bits.exe
  InstallerSha256: DD962BC788D7D955B04E163E7E1A6620B573ADC379BF2EA2A2C25585782B4DCA
ManifestType: installer
ManifestVersion: 1.6.0
